In [1]:
# Import Libraries

import pandas as pd
import joblib

In [2]:
# Load Saved Model

model = joblib.load("../models/random_forest_model.pkl")

print("Model Loaded Successfully")

Model Loaded Successfully

In [3]:
# Load Final Feature Dataset

features = pd.read_csv("../Dataset/final_features.csv")

features.head()

,user,login_count,logoff_count,usb_connect_count,usb_disconnect_count,email_count,file_activity_count,unique_pc_count,after_hours_login,weekend_activity,attachment_count
0,AAE0190,692,346,0.0,0.0,4711,0.0,1,0.0,0.0,953.0
1,AAF0535,328,164,346.0,342.0,480,357.0,1,0.0,0.0,187.0
2,AAF0791,692,346,0.0,0.0,3012,0.0,1,0.0,0.0,0.0
3,AAL0706,692,346,0.0,0.0,336,0.0,1,346.0,0.0,71.0
4,AAM0658,458,229,7.0,6.0,659,31.0,1,234.0,2.0,275.0

In [4]:
# Select Sample User

sample = features.drop(columns=["user"]).iloc[[0]]

sample

,login_count,logoff_count,usb_connect_count,usb_disconnect_count,email_count,file_activity_count,unique_pc_count,after_hours_login,weekend_activity,attachment_count
0,692,346,0.0,0.0,4711,0.0,1,0.0,0.0,953.0

In [5]:
# Predict

prediction = model.predict(sample)

print(prediction)

[0]

In [7]:
# Display Result

if prediction[0] == 1:
    print("⚠️ Insider Threat Detected")
else:
    print("✅ Normal User")

✅ Normal User